### ISSUE TITLE
Uninitialized constant  DocumentLibrary::IssuePatch::InstanceMethods::RedmineTrackControl

### ISSUE THREAD

**Issue by luizpra** [Mordorreal/redmine_document_library_gdrive#10]
Hi there,

I'm getting this error after plugin configuration, it happens at all issue edit (projects with and withtout Redmine document library gdrive)

Processing by IssuesController#show as HTML
  Parameters: {"id"=>"4"}
  Current user: luiz (id=1)
  Rendered issues/_action_menu.html.erb (10.6ms)
  Rendered plugins/redmine_document_library_gdrive/app/views/issues/_show_workspace_link.html.erb (12.7ms)
  Rendered issues/show.html.erb within layouts/base (71.3ms)
Completed 500 Internal Server Error in 219ms (ActiveRecord: 30.9ms)

ActionView::Template::Error (uninitialized constant DocumentLibrary::IssuePatch::InstanceMethods::RedmineTrackControl):
    1:
    2: <% if issue.visible_with_gdrive? && project.module_enabled?(:redmine_document_library_gdrive)%>
    3:   <table>
    4:     <hr>
    5:     <tr>
  plugins/redmine_document_library_gdrive/lib/document_library/issue_patch.rb:95:in `visible_with_gdrive?'
  plugins/redmine_document_library_gdrive/app/views/issues/_show_workspace_link.html.erb:2:in `_plugins_redmine_document_library_gdrive_app_views_issues__show_workspace_link_html_erb___1321871166314509105_69978498731800'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/show.html.erb:97:in `_app_views_issues_show_html_erb___3315341140169410239_69978497586920'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Any idea?

**Comment by Mordorreal** [comment]
Sorry, but no. I used it a long time ago last time. Re-check configuration. Maybe something changed in redmine api.
