### ISSUE TITLE
Callback in readme

### ISSUE THREAD

**Issue by sitehatchery** [Mordorreal/redmine_document_library_gdrive#8]
I appologize if this is the wrong place for this, but the readme documentation makes mention of two callback URLs to add to the Google project. However, Google doesn't seem to allow callbacks to be added to projects through their interface. Is there something that needs to be clarified in the readme file or will the code no longer work with the current Google OAuth API?

**Comment by Mordorreal** [comment]
Your callback in add-in config and in google console must be same:

![screenshot-console developers google com-2017-12-15-16-57-28-699](https://user-images.githubusercontent.com/8039537/34045261-28ecbf88-e1b9-11e7-992b-5632c5bd4568.png)

**Comment by sitehatchery** [comment]
Thanks so much. I was able to find where to add this.

I apologize if this is not the place to ask this. Please direct me to
another method if you would rather me communicate with you via another
means. My direct email is jason@sitehatchery.com.

Now, I have a client ID and a secret. I added this in my
additional_environment.rb (and also tried application.rb) file:

GOOGLE_CLIENT_ID = '{my client ID}'
GOOGLE_CLIENT_SECRET = '{my secret}'

I also tried setting the environment variable in Passenger.

When I restarted Redmine and viewed the configuration page, nothing
happened.

When I try to view an issue, I get a 500 error. Here is the stack trace:
I, [2017-12-16T01:34:21.487286 #26536]  INFO -- : Started GET
"/issues/5714" for 209.59.185.4 at 2017-12-16 01:34:21 -0800
I, [2017-12-16T01:34:21.488803 #26536]  INFO -- : Processing by
IssuesController#show as HTML
I, [2017-12-16T01:34:21.488858 #26536]  INFO -- :   Parameters:
{"id"=>"5714"}
I, [2017-12-16T01:34:21.492729 #26536]  INFO -- :   Current user: admin
(id=1)
I, [2017-12-16T01:34:21.533396 #26536]  INFO -- :   Rendered
issues/_action_menu.html.erb (3.2ms)
I, [2017-12-16T01:34:21.558427 #26536]  INFO -- :   Rendered
plugins/redmine_document_library_gdrive/app/views/issues/_show_workspace_link.html.erb
(4.6ms)
I, [2017-12-16T01:34:21.558550 #26536]  INFO -- :   Rendered
issues/show.html.erb within layouts/base (28.6ms)
I, [2017-12-16T01:34:21.558736 #26536]  INFO -- : Completed 500 Internal
Server Error in 70ms (ActiveRecord: 4.6ms)
F, [2017-12-16T01:34:21.560493 #26536] FATAL -- :
ActionView::Template::Error (uninitialized constant
DocumentLibrary::IssuePatch::InstanceMethods::RedmineTrackControl):
    1:
    2: <% if issue.visible_with_gdrive? &&
project.module_enabled?(:redmine_document_library_gdrive)%>
    3:   <table>
    4:     <hr>
    5:     <tr>

plugins/redmine_document_library_gdrive/lib/document_library/issue_patch.rb:95:in
`visible_with_gdrive?'

plugins/redmine_document_library_gdrive/app/views/issues/_show_workspace_link.html.erb:2:in
`_plugins_redmine_document_library_gdrive_app_views_issues__show_workspace_link_html_erb__2243748063178765325_70356317919680'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/show.html.erb:97:in
`_app_views_issues_show_html_erb__2086469470777584964_70356315499060'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Here are my settings:

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.7.1
  Filesystem
Redmine plugins:
  redmine_ckeditor               1.1.5
  redmine_contacts               4.1.1
  redmine_contacts_invoices      4.1.6
  time_logger                    0.5.4

**Comment by Mordorreal** [comment]
You need to set system ENV https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps <https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps>
Don’t put your keys in files! This is unsafe.

**Comment by sitehatchery** [comment]
I'm getting this error:

ActionView::Template::Error (uninitialized constant
DocumentLibrary::IssuePatch::InstanceMethods::RedmineTrackControl):
    1:
    2: <% if issue.visible_with_gdrive? &&
project.module_enabled?(:redmine_document_library_gdrive)%>
    3:   <table>
    4:     <hr>
    5:     <tr>


Here are my specs:

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2


Jason Cox
(530) 680-2734

*Sign Up for Our Newsletter* <http://eepurl.com/dN9gg>

Website <https://www.sitehatchery.com>  |  Facebook
<https://www.facebook.com/sitehatchery>  |  Yelp
<https://www.yelp.com/biz/sitehatchery-chico?osq=sitehatchery.com>  |
Google+ <https://plus.google.com/115745181796040379411>  |  Twitter
<http://www.twitter.com/sitehatchery>
